In [2]:
import pandas as pd
import seaborn as sns
from sklearn import linear_model
# from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as smf

In [3]:
tips = sns.load_dataset("tips")

In [4]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
model = smf.ols('tip ~ total_bill', data=tips)

In [6]:
results = model.fit()

In [7]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     203.4
Date:                Tue, 16 Dec 2025   Prob (F-statistic):           6.69e-34
Time:                        12:03:19   Log-Likelihood:                -350.54
No. Observations:                 244   AIC:                             705.1
Df Residuals:                     242   BIC:                             712.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9203      0.160      5.761      0.000       0.606       1.235
total_bill     0.1050      0.007     14.260      0.000       0.091       0.120
==============================================================================
Omnibus:                       20.185   Durbin-Watson:                   2.151
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               37.750
Skew:                           0.443   Prob(JB):                     6.35e-09
Kurtosis:                       4.711   Cond. No.                         53.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
model = smf.ols('tip ~ total_bill + sex + smoker + day + size', data=tips)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.470
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     29.90
Date:                Tue, 16 Dec 2025   Prob (F-statistic):           2.12e-29
Time:                        12:06:03   Log-Likelihood:                -347.49
No. Observations:                 244   AIC:                             711.0
Df Residuals:                     236   BIC:                             739.0
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.5917      0.255      2.318      0.021       0.089       1.095
sex[T.Female]     0.0324      0.141      0.230      0.819      -0.246       0.311
smoker[T.No]      0.0849      0.146      0.581      0.561      -0.203       0.372
day[T.Fri]        0.1198      0.279      0.430      0.668      -0.429       0.669
day[T.Sat]       -0.0261      0.175     -0.149      0.882      -0.371       0.319
day[T.Sun]        0.0701      0.181      0.386      0.700      -0.287       0.428
total_bill        0.0943      0.010      9.922      0.000       0.076       0.113
size              0.1770      0.089      1.987      0.048       0.001       0.353
==============================================================================
Omnibus:                       27.933   Durbin-Watson:                   2.095
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               52.677
Skew:                           0.608   Prob(JB):                     3.64e-12
Kurtosis:                       4.924   Cond. No.                         117.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
from sklearn import linear_model
# from sklearn.linear_model import LinearRegression

In [11]:
lr = linear_model.LinearRegression()
#lr = LinearRegression()

In [12]:
lr.fit(X=tips["total_bill"], y=tips["tip"])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [15]:
results = lr.fit(X=tips[["total_bill"]], y=tips["tip"])
results

LinearRegression()

In [16]:
results.coef_

array([0.10502452])

In [17]:
results.intercept_ 

np.float64(0.9202696135546731)

In [18]:
lr = linear_model.LinearRegression()
results = lr.fit(X=tips[["total_bill", "size", "smoker"]], y=tips["tip"])
results

ValueError: could not convert string to float: 'No'

In [19]:
tips_subset = tips[["total_bill", "tip", "size", "smoker"]]
tips_subset

total_bill   tip  size smoker
0         16.99  1.01     2     No
1         10.34  1.66     3     No
2         21.01  3.50     3     No
3         23.68  3.31     2     No
4         24.59  3.61     4     No
..          ...   ...   ...    ...
239       29.03  5.92     3     No
240       27.18  2.00     2    Yes
241       22.67  2.00     2    Yes
242       17.82  1.75     2     No
243       18.78  3.00     2     No

[244 rows x 4 columns]

In [21]:
pd.get_dummies(tips_subset)

total_bill   tip  size  smoker_Yes  smoker_No
0         16.99  1.01     2       False       True
1         10.34  1.66     3       False       True
2         21.01  3.50     3       False       True
3         23.68  3.31     2       False       True
4         24.59  3.61     4       False       True
..          ...   ...   ...         ...        ...
239       29.03  5.92     3       False       True
240       27.18  2.00     2        True      False
241       22.67  2.00     2        True      False
242       17.82  1.75     2       False       True
243       18.78  3.00     2       False       True

[244 rows x 5 columns]

In [25]:
tips_dummy = pd.get_dummies(tips_subset, drop_first=True)
tips_dummy

total_bill   tip  size  smoker_No
0         16.99  1.01     2       True
1         10.34  1.66     3       True
2         21.01  3.50     3       True
3         23.68  3.31     2       True
4         24.59  3.61     4       True
..          ...   ...   ...        ...
239       29.03  5.92     3       True
240       27.18  2.00     2      False
241       22.67  2.00     2      False
242       17.82  1.75     2       True
243       18.78  3.00     2       True

[244 rows x 4 columns]

In [26]:
y = tips_dummy.pop("tip")

In [29]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [30]:
tips_dummy

total_bill  size  smoker_No
0         16.99     2       True
1         10.34     3       True
2         21.01     3       True
3         23.68     2       True
4         24.59     4       True
..          ...   ...        ...
239       29.03     3       True
240       27.18     2      False
241       22.67     2      False
242       17.82     2       True
243       18.78     2       True

[244 rows x 3 columns]

In [31]:
lr = linear_model.LinearRegression()
results = lr.fit(X=tips_dummy, y=y)

In [32]:
results.coef_

array([0.09388839, 0.18033156, 0.08343255])

In [33]:
tips_dummy.columns

Index(['total_bill', 'size', 'smoker_No'], dtype='object')

In [35]:
results.predict(tips_dummy)

array([2.66484238, 2.22081616, 3.22260527, 3.29295571, 3.73905727,
       3.80477915, 1.89307982, 3.95406169, 2.48176002, 2.45734904,
       2.03391241, 4.74084639, 2.51743761, 3.16070479, 2.46204346,
       3.09579009, 2.21987727, 2.77945208, 2.84329618, 3.18880545,
       2.75215859, 2.97467407, 2.55029855, 5.13142209, 2.93054653,
       3.10249399, 2.32496641, 2.26112231, 3.1070567 , 2.9145855 ,
       1.96631277, 3.15319372, 2.48363779, 3.37289255, 2.73901421,
       3.50896486, 2.78132984, 2.83954064, 3.00478421, 4.18590015,
       2.75597998, 2.70896993, 2.3784828 , 1.97851826, 4.28454882,
       2.78689729, 3.15681755, 4.4723256 , 3.93052373, 2.76342519,
       2.24703905, 2.03579017, 4.69859661, 2.00292924, 3.83012901,
       2.89956336, 4.91560691, 3.54927101, 2.04155159, 5.96233434,
       2.89124152, 2.28284475, 2.02089615, 3.06412787, 2.90150698,
       3.13528907, 2.61414265, 1.09415188, 2.96904077, 2.39551082,
       2.19821709, 2.85268502, 3.50808824, 3.35974458, 2.45265

In [36]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64